version: '3'
services:
  nagios:
    image: "srbooz/nagios-core:1.0"
    build: 
      context: "./"
      dockerfile: "Dockerfile"
    container_name: nagios-eva
    ports:
      - "8080:80"
    restart: always